apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: {{ index .Values.SERVICES .Values.SELECTED "NAMESPACE" }}
spec:
  limits:
  - default:
      cpu: {{ index .Values.SERVICES .Values.SELECTED "LIMITES" "SPACE" "LIMITS" "CPU" }}
      memory: {{ index .Values.SERVICES .Values.SELECTED "LIMITES" "SPACE" "LIMITS" "MEM" }}
    defaultRequest:
      cpu: {{ index .Values.SERVICES .Values.SELECTED "LIMITES" "SPACE" "DEFAULT" "CPU" }}
      memory: {{ index .Values.SERVICES .Values.SELECTED "LIMITES" "SPACE" "DEFAULT" "MEM" }}
    type: Container