apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-api-deployment
spec:
  selector:
    matchLabels:
      app: multi-api
  template:
    metadata:
      labels:
        app: multi-api
    spec:
      containers:
      - name: service-acct-auth-container
        image: service-acct-auth
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
