apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-service-acct-auth-v0-0-2
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: service-acct-auth
      tier: backend
      version: v0-0-2
  template:
    metadata:
      labels: 
        app: service-acct-auth
        tier: backend
        version: v0-0-2
    spec:
      containers:
      - name: container-service-acct-auth
        image: localhost:5000/service-acct-auth:V0.0.2
        ports:
        - containerPort: 50051
          protocol: TCP
        env:
        - name: APP_PORT
          value: "50051"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
