---
POSTGRESQL:
  DATABASE_URL: "postgres://postgres:5432@host.docker.internal:5432/test_db"

SERVICE-HTTP-SEND-HTML:
  PORT: ":8080"
  HTML_DIR: "../../html"
  LOG_FILE:
    INFO_LEVEL: "infoHTTP.log"
    ERROR_LEVEL: "errorHTTP.log"
    PANIC_LEVEL: "panicHTTP.log"

SERVICE-ACCT-AUTH:
  NETWORK_SERVER: "tcp"
  PORT: ":50051"
  LOG_FILE: "total.log"
  JWT_SECRET: "asdfghjk"

SERVICE-ORDER-PAY:
  NETWORK_SERVER: "tcp"
  PORT: ":50052"

SERVICE-DATA-CUSTOMER:
  NETWORK_SERVER: "tcp"
  PORT: ":50054"
...