---
POSTGRESQL:
  DATABASE_URL: "postgres://postgres:5432@localhost:5432/test_db"

SEND_HTML_SEVER:
  PORT: ":8080"
  HTML_DIR: "../../html"
  LOG_FILE:
    INFO_LEVEL: "infoHTTP.log"
    ERROR_LEVEL: "errorHTTP.log"
    PANIC_LEVEL: "panicHTTP.log"
...