// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: basic.proto

package basic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CUSTOMER
type CustomerAut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginCustomer    string `protobuf:"bytes,1,opt,name=login_customer,json=loginCustomer,proto3" json:"login_customer,omitempty"`
	PasswortCustomer string `protobuf:"bytes,2,opt,name=passwort_customer,json=passwortCustomer,proto3" json:"passwort_customer,omitempty"`
}

func (x *CustomerAut) Reset() {
	*x = CustomerAut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerAut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerAut) ProtoMessage() {}

func (x *CustomerAut) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerAut.ProtoReflect.Descriptor instead.
func (*CustomerAut) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerAut) GetLoginCustomer() string {
	if x != nil {
		return x.LoginCustomer
	}
	return ""
}

func (x *CustomerAut) GetPasswortCustomer() string {
	if x != nil {
		return x.PasswortCustomer
	}
	return ""
}

type CustomerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerCountry string `protobuf:"bytes,1,opt,name=customer_country,json=customerCountry,proto3" json:"customer_country,omitempty"`
	CustomerCiry    string `protobuf:"bytes,2,opt,name=customer_ciry,json=customerCiry,proto3" json:"customer_ciry,omitempty"`
}

func (x *CustomerInfo) Reset() {
	*x = CustomerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerInfo) ProtoMessage() {}

func (x *CustomerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerInfo.ProtoReflect.Descriptor instead.
func (*CustomerInfo) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerInfo) GetCustomerCountry() string {
	if x != nil {
		return x.CustomerCountry
	}
	return ""
}

func (x *CustomerInfo) GetCustomerCiry() string {
	if x != nil {
		return x.CustomerCiry
	}
	return ""
}

type CustomerChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerAutNew *CustomerAut  `protobuf:"bytes,1,opt,name=customer_aut_new,json=customerAutNew,proto3" json:"customer_aut_new,omitempty"`
	CustomerAutOld *CustomerAut  `protobuf:"bytes,2,opt,name=customer_aut_old,json=customerAutOld,proto3" json:"customer_aut_old,omitempty"`
	CustomerInfo   *CustomerInfo `protobuf:"bytes,3,opt,name=customer_info,json=customerInfo,proto3" json:"customer_info,omitempty"`
}

func (x *CustomerChange) Reset() {
	*x = CustomerChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerChange) ProtoMessage() {}

func (x *CustomerChange) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerChange.ProtoReflect.Descriptor instead.
func (*CustomerChange) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerChange) GetCustomerAutNew() *CustomerAut {
	if x != nil {
		return x.CustomerAutNew
	}
	return nil
}

func (x *CustomerChange) GetCustomerAutOld() *CustomerAut {
	if x != nil {
		return x.CustomerAutOld
	}
	return nil
}

func (x *CustomerChange) GetCustomerInfo() *CustomerInfo {
	if x != nil {
		return x.CustomerInfo
	}
	return nil
}

// WAREHOUSE
type WarehouseAut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginWarehouse    string `protobuf:"bytes,1,opt,name=login_warehouse,json=loginWarehouse,proto3" json:"login_warehouse,omitempty"`
	PasswortWarehouse string `protobuf:"bytes,2,opt,name=passwort_warehouse,json=passwortWarehouse,proto3" json:"passwort_warehouse,omitempty"`
}

func (x *WarehouseAut) Reset() {
	*x = WarehouseAut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WarehouseAut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseAut) ProtoMessage() {}

func (x *WarehouseAut) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseAut.ProtoReflect.Descriptor instead.
func (*WarehouseAut) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{3}
}

func (x *WarehouseAut) GetLoginWarehouse() string {
	if x != nil {
		return x.LoginWarehouse
	}
	return ""
}

func (x *WarehouseAut) GetPasswortWarehouse() string {
	if x != nil {
		return x.PasswortWarehouse
	}
	return ""
}

type WarehouseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WarehouseName       string  `protobuf:"bytes,1,opt,name=warehouse_name,json=warehouseName,proto3" json:"warehouse_name,omitempty"`
	WarehouseCountry    string  `protobuf:"bytes,2,opt,name=warehouse_country,json=warehouseCountry,proto3" json:"warehouse_country,omitempty"`
	WarehouseCity       string  `protobuf:"bytes,3,opt,name=warehouse_city,json=warehouseCity,proto3" json:"warehouse_city,omitempty"`
	WarehouseCommission float32 `protobuf:"fixed32,4,opt,name=warehouse_commission,json=warehouseCommission,proto3" json:"warehouse_commission,omitempty"`
	WarehouseNote       string  `protobuf:"bytes,5,opt,name=warehouse_note,json=warehouseNote,proto3" json:"warehouse_note,omitempty"`
}

func (x *WarehouseInfo) Reset() {
	*x = WarehouseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WarehouseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseInfo) ProtoMessage() {}

func (x *WarehouseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseInfo.ProtoReflect.Descriptor instead.
func (*WarehouseInfo) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{4}
}

func (x *WarehouseInfo) GetWarehouseName() string {
	if x != nil {
		return x.WarehouseName
	}
	return ""
}

func (x *WarehouseInfo) GetWarehouseCountry() string {
	if x != nil {
		return x.WarehouseCountry
	}
	return ""
}

func (x *WarehouseInfo) GetWarehouseCity() string {
	if x != nil {
		return x.WarehouseCity
	}
	return ""
}

func (x *WarehouseInfo) GetWarehouseCommission() float32 {
	if x != nil {
		return x.WarehouseCommission
	}
	return 0
}

func (x *WarehouseInfo) GetWarehouseNote() string {
	if x != nil {
		return x.WarehouseNote
	}
	return ""
}

type WarehouseChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WarehouseAutNew *WarehouseAut  `protobuf:"bytes,1,opt,name=warehouse_aut_new,json=warehouseAutNew,proto3" json:"warehouse_aut_new,omitempty"`
	WarehouseAutOld *WarehouseAut  `protobuf:"bytes,2,opt,name=warehouse_aut_old,json=warehouseAutOld,proto3" json:"warehouse_aut_old,omitempty"`
	WarehouseInfo   *WarehouseInfo `protobuf:"bytes,3,opt,name=warehouse_info,json=warehouseInfo,proto3" json:"warehouse_info,omitempty"`
}

func (x *WarehouseChange) Reset() {
	*x = WarehouseChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WarehouseChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseChange) ProtoMessage() {}

func (x *WarehouseChange) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseChange.ProtoReflect.Descriptor instead.
func (*WarehouseChange) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{5}
}

func (x *WarehouseChange) GetWarehouseAutNew() *WarehouseAut {
	if x != nil {
		return x.WarehouseAutNew
	}
	return nil
}

func (x *WarehouseChange) GetWarehouseAutOld() *WarehouseAut {
	if x != nil {
		return x.WarehouseAutOld
	}
	return nil
}

func (x *WarehouseChange) GetWarehouseInfo() *WarehouseInfo {
	if x != nil {
		return x.WarehouseInfo
	}
	return nil
}

type WarehouseWalletInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletMoneyAvailable float32 `protobuf:"fixed32,1,opt,name=wallet_money_available,json=walletMoneyAvailable,proto3" json:"wallet_money_available,omitempty"`
	WalletMoneyBlocked   float32 `protobuf:"fixed32,2,opt,name=wallet_money_blocked,json=walletMoneyBlocked,proto3" json:"wallet_money_blocked,omitempty"`
	CommissionPercentage float32 `protobuf:"fixed32,3,opt,name=commission_percentage,json=commissionPercentage,proto3" json:"commission_percentage,omitempty"`
}

func (x *WarehouseWalletInfo) Reset() {
	*x = WarehouseWalletInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WarehouseWalletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseWalletInfo) ProtoMessage() {}

func (x *WarehouseWalletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseWalletInfo.ProtoReflect.Descriptor instead.
func (*WarehouseWalletInfo) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{6}
}

func (x *WarehouseWalletInfo) GetWalletMoneyAvailable() float32 {
	if x != nil {
		return x.WalletMoneyAvailable
	}
	return 0
}

func (x *WarehouseWalletInfo) GetWalletMoneyBlocked() float32 {
	if x != nil {
		return x.WalletMoneyBlocked
	}
	return 0
}

func (x *WarehouseWalletInfo) GetCommissionPercentage() float32 {
	if x != nil {
		return x.CommissionPercentage
	}
	return 0
}

type ReceivingGoods struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameVendor  string `protobuf:"bytes,1,opt,name=name_vendor,json=nameVendor,proto3" json:"name_vendor,omitempty"`
	NameGoods   string `protobuf:"bytes,2,opt,name=name_goods,json=nameGoods,proto3" json:"name_goods,omitempty"`
	AmountGoods uint32 `protobuf:"varint,3,opt,name=amount_goods,json=amountGoods,proto3" json:"amount_goods,omitempty"`
}

func (x *ReceivingGoods) Reset() {
	*x = ReceivingGoods{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceivingGoods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivingGoods) ProtoMessage() {}

func (x *ReceivingGoods) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivingGoods.ProtoReflect.Descriptor instead.
func (*ReceivingGoods) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{7}
}

func (x *ReceivingGoods) GetNameVendor() string {
	if x != nil {
		return x.NameVendor
	}
	return ""
}

func (x *ReceivingGoods) GetNameGoods() string {
	if x != nil {
		return x.NameGoods
	}
	return ""
}

func (x *ReceivingGoods) GetAmountGoods() uint32 {
	if x != nil {
		return x.AmountGoods
	}
	return 0
}

type ReceivingGoodsARRAY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceivingGoodsArray []*ReceivingGoods `protobuf:"bytes,1,rep,name=receiving_goods_array,json=receivingGoodsArray,proto3" json:"receiving_goods_array,omitempty"`
}

func (x *ReceivingGoodsARRAY) Reset() {
	*x = ReceivingGoodsARRAY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceivingGoodsARRAY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivingGoodsARRAY) ProtoMessage() {}

func (x *ReceivingGoodsARRAY) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivingGoodsARRAY.ProtoReflect.Descriptor instead.
func (*ReceivingGoodsARRAY) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{8}
}

func (x *ReceivingGoodsARRAY) GetReceivingGoodsArray() []*ReceivingGoods {
	if x != nil {
		return x.ReceivingGoodsArray
	}
	return nil
}

// VENDOR
type VendorAut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginVendor    string `protobuf:"bytes,1,opt,name=login_vendor,json=loginVendor,proto3" json:"login_vendor,omitempty"`
	PasswortVendor string `protobuf:"bytes,2,opt,name=passwort_vendor,json=passwortVendor,proto3" json:"passwort_vendor,omitempty"`
}

func (x *VendorAut) Reset() {
	*x = VendorAut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VendorAut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorAut) ProtoMessage() {}

func (x *VendorAut) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorAut.ProtoReflect.Descriptor instead.
func (*VendorAut) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{9}
}

func (x *VendorAut) GetLoginVendor() string {
	if x != nil {
		return x.LoginVendor
	}
	return ""
}

func (x *VendorAut) GetPasswortVendor() string {
	if x != nil {
		return x.PasswortVendor
	}
	return ""
}

type VendorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VendorName string `protobuf:"bytes,1,opt,name=vendor_name,json=vendorName,proto3" json:"vendor_name,omitempty"`
}

func (x *VendorInfo) Reset() {
	*x = VendorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VendorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorInfo) ProtoMessage() {}

func (x *VendorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorInfo.ProtoReflect.Descriptor instead.
func (*VendorInfo) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{10}
}

func (x *VendorInfo) GetVendorName() string {
	if x != nil {
		return x.VendorName
	}
	return ""
}

type VendorChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VendorAutNew *VendorAut  `protobuf:"bytes,1,opt,name=vendor_aut_new,json=vendorAutNew,proto3" json:"vendor_aut_new,omitempty"`
	VendorAutOld *VendorAut  `protobuf:"bytes,2,opt,name=vendor_aut_old,json=vendorAutOld,proto3" json:"vendor_aut_old,omitempty"`
	VendorInfo   *VendorInfo `protobuf:"bytes,3,opt,name=vendor_info,json=vendorInfo,proto3" json:"vendor_info,omitempty"`
}

func (x *VendorChange) Reset() {
	*x = VendorChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VendorChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorChange) ProtoMessage() {}

func (x *VendorChange) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorChange.ProtoReflect.Descriptor instead.
func (*VendorChange) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{11}
}

func (x *VendorChange) GetVendorAutNew() *VendorAut {
	if x != nil {
		return x.VendorAutNew
	}
	return nil
}

func (x *VendorChange) GetVendorAutOld() *VendorAut {
	if x != nil {
		return x.VendorAutOld
	}
	return nil
}

func (x *VendorChange) GetVendorInfo() *VendorInfo {
	if x != nil {
		return x.VendorInfo
	}
	return nil
}

// OTHERS
type LoginPass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to AccountChoice:
	//
	//	*LoginPass_CustomerLoginPass
	//	*LoginPass_WarehouseLoginPass
	//	*LoginPass_VendorLoginPass
	AccountChoice isLoginPass_AccountChoice `protobuf_oneof:"account_choice"`
}

func (x *LoginPass) Reset() {
	*x = LoginPass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPass) ProtoMessage() {}

func (x *LoginPass) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginPass.ProtoReflect.Descriptor instead.
func (*LoginPass) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{12}
}

func (m *LoginPass) GetAccountChoice() isLoginPass_AccountChoice {
	if m != nil {
		return m.AccountChoice
	}
	return nil
}

func (x *LoginPass) GetCustomerLoginPass() *CustomerAut {
	if x, ok := x.GetAccountChoice().(*LoginPass_CustomerLoginPass); ok {
		return x.CustomerLoginPass
	}
	return nil
}

func (x *LoginPass) GetWarehouseLoginPass() *WarehouseAut {
	if x, ok := x.GetAccountChoice().(*LoginPass_WarehouseLoginPass); ok {
		return x.WarehouseLoginPass
	}
	return nil
}

func (x *LoginPass) GetVendorLoginPass() *VendorAut {
	if x, ok := x.GetAccountChoice().(*LoginPass_VendorLoginPass); ok {
		return x.VendorLoginPass
	}
	return nil
}

type isLoginPass_AccountChoice interface {
	isLoginPass_AccountChoice()
}

type LoginPass_CustomerLoginPass struct {
	CustomerLoginPass *CustomerAut `protobuf:"bytes,1,opt,name=customer_login_pass,json=customerLoginPass,proto3,oneof"`
}

type LoginPass_WarehouseLoginPass struct {
	WarehouseLoginPass *WarehouseAut `protobuf:"bytes,2,opt,name=warehouse_login_pass,json=warehouseLoginPass,proto3,oneof"`
}

type LoginPass_VendorLoginPass struct {
	VendorLoginPass *VendorAut `protobuf:"bytes,3,opt,name=vendor_login_pass,json=vendorLoginPass,proto3,oneof"`
}

func (*LoginPass_CustomerLoginPass) isLoginPass_AccountChoice() {}

func (*LoginPass_WarehouseLoginPass) isLoginPass_AccountChoice() {}

func (*LoginPass_VendorLoginPass) isLoginPass_AccountChoice() {}

type AccountInfoChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to AccountInfo:
	//
	//	*AccountInfoChange_CustomerChange
	//	*AccountInfoChange_WarehouseChange
	//	*AccountInfoChange_VendorChange
	AccountInfo isAccountInfoChange_AccountInfo `protobuf_oneof:"account_info"`
}

func (x *AccountInfoChange) Reset() {
	*x = AccountInfoChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoChange) ProtoMessage() {}

func (x *AccountInfoChange) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoChange.ProtoReflect.Descriptor instead.
func (*AccountInfoChange) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{13}
}

func (m *AccountInfoChange) GetAccountInfo() isAccountInfoChange_AccountInfo {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

func (x *AccountInfoChange) GetCustomerChange() *CustomerChange {
	if x, ok := x.GetAccountInfo().(*AccountInfoChange_CustomerChange); ok {
		return x.CustomerChange
	}
	return nil
}

func (x *AccountInfoChange) GetWarehouseChange() *WarehouseChange {
	if x, ok := x.GetAccountInfo().(*AccountInfoChange_WarehouseChange); ok {
		return x.WarehouseChange
	}
	return nil
}

func (x *AccountInfoChange) GetVendorChange() *VendorChange {
	if x, ok := x.GetAccountInfo().(*AccountInfoChange_VendorChange); ok {
		return x.VendorChange
	}
	return nil
}

type isAccountInfoChange_AccountInfo interface {
	isAccountInfoChange_AccountInfo()
}

type AccountInfoChange_CustomerChange struct {
	CustomerChange *CustomerChange `protobuf:"bytes,1,opt,name=customer_change,json=customerChange,proto3,oneof"`
}

type AccountInfoChange_WarehouseChange struct {
	WarehouseChange *WarehouseChange `protobuf:"bytes,2,opt,name=warehouse_change,json=warehouseChange,proto3,oneof"`
}

type AccountInfoChange_VendorChange struct {
	VendorChange *VendorChange `protobuf:"bytes,3,opt,name=vendor_change,json=vendorChange,proto3,oneof"`
}

func (*AccountInfoChange_CustomerChange) isAccountInfoChange_AccountInfo() {}

func (*AccountInfoChange_WarehouseChange) isAccountInfoChange_AccountInfo() {}

func (*AccountInfoChange_VendorChange) isAccountInfoChange_AccountInfo() {}

type StringJWT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StringJwt string `protobuf:"bytes,1,opt,name=string_jwt,json=stringJwt,proto3" json:"string_jwt,omitempty"`
}

func (x *StringJWT) Reset() {
	*x = StringJWT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringJWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringJWT) ProtoMessage() {}

func (x *StringJWT) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringJWT.ProtoReflect.Descriptor instead.
func (*StringJWT) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{14}
}

func (x *StringJWT) GetStringJwt() string {
	if x != nil {
		return x.StringJwt
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderUuid     string  `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	NameGoods     string  `protobuf:"bytes,2,opt,name=name_goods,json=nameGoods,proto3" json:"name_goods,omitempty"`
	NameVendor    string  `protobuf:"bytes,3,opt,name=name_vendor,json=nameVendor,proto3" json:"name_vendor,omitempty"`
	NameWarehouse string  `protobuf:"bytes,4,opt,name=name_warehouse,json=nameWarehouse,proto3" json:"name_warehouse,omitempty"`
	AmountGoods   uint32  `protobuf:"varint,5,opt,name=amount_goods,json=amountGoods,proto3" json:"amount_goods,omitempty"`
	PriceGoods    float32 `protobuf:"fixed32,6,opt,name=price_goods,json=priceGoods,proto3" json:"price_goods,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{15}
}

func (x *Order) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *Order) GetNameGoods() string {
	if x != nil {
		return x.NameGoods
	}
	return ""
}

func (x *Order) GetNameVendor() string {
	if x != nil {
		return x.NameVendor
	}
	return ""
}

func (x *Order) GetNameWarehouse() string {
	if x != nil {
		return x.NameWarehouse
	}
	return ""
}

func (x *Order) GetAmountGoods() uint32 {
	if x != nil {
		return x.AmountGoods
	}
	return 0
}

func (x *Order) GetPriceGoods() float32 {
	if x != nil {
		return x.PriceGoods
	}
	return 0
}

type OrdersCustomer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginCustomer string   `protobuf:"bytes,1,opt,name=login_customer,json=loginCustomer,proto3" json:"login_customer,omitempty"`
	Orders        []*Order `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *OrdersCustomer) Reset() {
	*x = OrdersCustomer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrdersCustomer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersCustomer) ProtoMessage() {}

func (x *OrdersCustomer) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersCustomer.ProtoReflect.Descriptor instead.
func (*OrdersCustomer) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{16}
}

func (x *OrdersCustomer) GetLoginCustomer() string {
	if x != nil {
		return x.LoginCustomer
	}
	return ""
}

func (x *OrdersCustomer) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ArrayOrdersCustomer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrdersCustomer []*OrdersCustomer `protobuf:"bytes,1,rep,name=orders_customer,json=ordersCustomer,proto3" json:"orders_customer,omitempty"`
}

func (x *ArrayOrdersCustomer) Reset() {
	*x = ArrayOrdersCustomer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayOrdersCustomer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayOrdersCustomer) ProtoMessage() {}

func (x *ArrayOrdersCustomer) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayOrdersCustomer.ProtoReflect.Descriptor instead.
func (*ArrayOrdersCustomer) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{17}
}

func (x *ArrayOrdersCustomer) GetOrdersCustomer() []*OrdersCustomer {
	if x != nil {
		return x.OrdersCustomer
	}
	return nil
}

var File_basic_proto protoreflect.FileDescriptor

var file_basic_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x22, 0x61, 0x0a, 0x0b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x41, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x74, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x74, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x22, 0x5e, 0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x63,
	0x69, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x43, 0x69, 0x72, 0x79, 0x22, 0xc6, 0x01, 0x0a, 0x0e, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x3c, 0x0a, 0x10, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x61, 0x75, 0x74, 0x5f, 0x6e, 0x65, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x41, 0x75, 0x74, 0x52, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x41, 0x75, 0x74, 0x4e, 0x65, 0x77, 0x12, 0x3c, 0x0a, 0x10, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x61, 0x75, 0x74, 0x5f, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x41, 0x75, 0x74, 0x52, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x41, 0x75, 0x74, 0x4f, 0x6c, 0x64, 0x12, 0x38, 0x0a, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x66, 0x0a, 0x0c, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x75, 0x74,
	0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x74, 0x5f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x74, 0x57,
	0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x22, 0xe4, 0x01, 0x0a, 0x0d, 0x57, 0x61, 0x72,
	0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x2b, 0x0a, 0x11, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x77, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x25,
	0x0a, 0x0e, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x43, 0x69, 0x74, 0x79, 0x12, 0x31, 0x0a, 0x14, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x13, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x61, 0x72, 0x65,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x22,
	0xd0, 0x01, 0x0a, 0x0f, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x11, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x5f, 0x61, 0x75, 0x74, 0x5f, 0x6e, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x41, 0x75, 0x74, 0x52, 0x0f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x75,
	0x74, 0x4e, 0x65, 0x77, 0x12, 0x3f, 0x0a, 0x11, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x5f, 0x61, 0x75, 0x74, 0x5f, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x41, 0x75, 0x74, 0x52, 0x0f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x41,
	0x75, 0x74, 0x4f, 0x6c, 0x64, 0x12, 0x3b, 0x0a, 0x0e, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0xb2, 0x01, 0x0a, 0x13, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x16, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x14, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x30, 0x0a, 0x14, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x12,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x65, 0x64, 0x12, 0x33, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x22, 0x73, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x6d,
	0x65, 0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6e, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x61,
	0x6d, 0x65, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x60, 0x0a, 0x13,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x41, 0x52,
	0x52, 0x41, 0x59, 0x12, 0x49, 0x0a, 0x15, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e, 0x67,
	0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x13, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x22, 0x57,
	0x0a, 0x09, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x27,
	0x0a, 0x0f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x74, 0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x74, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x22, 0x2d, 0x0a, 0x0a, 0x56, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb2, 0x01, 0x0a, 0x0c, 0x56, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x0e, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x5f, 0x61, 0x75, 0x74, 0x5f, 0x6e, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x75,
	0x74, 0x52, 0x0c, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x75, 0x74, 0x4e, 0x65, 0x77, 0x12,
	0x36, 0x0a, 0x0e, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x61, 0x75, 0x74, 0x5f, 0x6f, 0x6c,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e,
	0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x75, 0x74, 0x52, 0x0c, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x41, 0x75, 0x74, 0x4f, 0x6c, 0x64, 0x12, 0x32, 0x0a, 0x0b, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x2e, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0a, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xec, 0x01, 0x0a, 0x09,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x12, 0x44, 0x0a, 0x13, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x41, 0x75, 0x74, 0x48, 0x00, 0x52, 0x11, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x12,
	0x47, 0x0a, 0x14, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x41,
	0x75, 0x74, 0x48, 0x00, 0x52, 0x12, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x12, 0x3e, 0x0a, 0x11, 0x76, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x56, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x41, 0x75, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x42, 0x10, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x22, 0xe6, 0x01, 0x0a, 0x11, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x40, 0x0a, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x43, 0x0a, 0x10, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x2e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x2a, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4a, 0x57, 0x54,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x6a, 0x77, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4a, 0x77, 0x74, 0x22,
	0xd1, 0x01, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65,
	0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x5f,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61,
	0x6d, 0x65, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x61, 0x6d, 0x65,
	0x5f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x22, 0x5d, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x06,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x22, 0x55, 0x0a, 0x13, 0x41, 0x72, 0x72, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x0f, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x0e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x6c, 0x69, 0x70, 0x68, 0x75, 0x6c,
	0x6b, 0x6f, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2d, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_basic_proto_rawDescOnce sync.Once
	file_basic_proto_rawDescData = file_basic_proto_rawDesc
)

func file_basic_proto_rawDescGZIP() []byte {
	file_basic_proto_rawDescOnce.Do(func() {
		file_basic_proto_rawDescData = protoimpl.X.CompressGZIP(file_basic_proto_rawDescData)
	})
	return file_basic_proto_rawDescData
}

var file_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_basic_proto_goTypes = []interface{}{
	(*CustomerAut)(nil),         // 0: basic.CustomerAut
	(*CustomerInfo)(nil),        // 1: basic.CustomerInfo
	(*CustomerChange)(nil),      // 2: basic.CustomerChange
	(*WarehouseAut)(nil),        // 3: basic.WarehouseAut
	(*WarehouseInfo)(nil),       // 4: basic.WarehouseInfo
	(*WarehouseChange)(nil),     // 5: basic.WarehouseChange
	(*WarehouseWalletInfo)(nil), // 6: basic.WarehouseWalletInfo
	(*ReceivingGoods)(nil),      // 7: basic.ReceivingGoods
	(*ReceivingGoodsARRAY)(nil), // 8: basic.ReceivingGoodsARRAY
	(*VendorAut)(nil),           // 9: basic.VendorAut
	(*VendorInfo)(nil),          // 10: basic.VendorInfo
	(*VendorChange)(nil),        // 11: basic.VendorChange
	(*LoginPass)(nil),           // 12: basic.LoginPass
	(*AccountInfoChange)(nil),   // 13: basic.AccountInfoChange
	(*StringJWT)(nil),           // 14: basic.StringJWT
	(*Order)(nil),               // 15: basic.Order
	(*OrdersCustomer)(nil),      // 16: basic.OrdersCustomer
	(*ArrayOrdersCustomer)(nil), // 17: basic.ArrayOrdersCustomer
}
var file_basic_proto_depIdxs = []int32{
	0,  // 0: basic.CustomerChange.customer_aut_new:type_name -> basic.CustomerAut
	0,  // 1: basic.CustomerChange.customer_aut_old:type_name -> basic.CustomerAut
	1,  // 2: basic.CustomerChange.customer_info:type_name -> basic.CustomerInfo
	3,  // 3: basic.WarehouseChange.warehouse_aut_new:type_name -> basic.WarehouseAut
	3,  // 4: basic.WarehouseChange.warehouse_aut_old:type_name -> basic.WarehouseAut
	4,  // 5: basic.WarehouseChange.warehouse_info:type_name -> basic.WarehouseInfo
	7,  // 6: basic.ReceivingGoodsARRAY.receiving_goods_array:type_name -> basic.ReceivingGoods
	9,  // 7: basic.VendorChange.vendor_aut_new:type_name -> basic.VendorAut
	9,  // 8: basic.VendorChange.vendor_aut_old:type_name -> basic.VendorAut
	10, // 9: basic.VendorChange.vendor_info:type_name -> basic.VendorInfo
	0,  // 10: basic.LoginPass.customer_login_pass:type_name -> basic.CustomerAut
	3,  // 11: basic.LoginPass.warehouse_login_pass:type_name -> basic.WarehouseAut
	9,  // 12: basic.LoginPass.vendor_login_pass:type_name -> basic.VendorAut
	2,  // 13: basic.AccountInfoChange.customer_change:type_name -> basic.CustomerChange
	5,  // 14: basic.AccountInfoChange.warehouse_change:type_name -> basic.WarehouseChange
	11, // 15: basic.AccountInfoChange.vendor_change:type_name -> basic.VendorChange
	15, // 16: basic.OrdersCustomer.orders:type_name -> basic.Order
	16, // 17: basic.ArrayOrdersCustomer.orders_customer:type_name -> basic.OrdersCustomer
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_basic_proto_init() }
func file_basic_proto_init() {
	if File_basic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_basic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerAut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WarehouseAut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WarehouseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WarehouseChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WarehouseWalletInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceivingGoods); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceivingGoodsARRAY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VendorAut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VendorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VendorChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginPass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringJWT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrdersCustomer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayOrdersCustomer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_basic_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*LoginPass_CustomerLoginPass)(nil),
		(*LoginPass_WarehouseLoginPass)(nil),
		(*LoginPass_VendorLoginPass)(nil),
	}
	file_basic_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*AccountInfoChange_CustomerChange)(nil),
		(*AccountInfoChange_WarehouseChange)(nil),
		(*AccountInfoChange_VendorChange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_basic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_basic_proto_goTypes,
		DependencyIndexes: file_basic_proto_depIdxs,
		MessageInfos:      file_basic_proto_msgTypes,
	}.Build()
	File_basic_proto = out.File
	file_basic_proto_rawDesc = nil
	file_basic_proto_goTypes = nil
	file_basic_proto_depIdxs = nil
}
