// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: basic.proto

package basic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatusEnum int32

const (
	OrderStatusEnum_UNSPECIFIED OrderStatusEnum = 0
	OrderStatusEnum_UNCONFIRMED OrderStatusEnum = 1
	OrderStatusEnum_CONFIRNED   OrderStatusEnum = 2
	OrderStatusEnum_COMPLETED   OrderStatusEnum = 3
)

// Enum value maps for OrderStatusEnum.
var (
	OrderStatusEnum_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNCONFIRMED",
		2: "CONFIRNED",
		3: "COMPLETED",
	}
	OrderStatusEnum_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UNCONFIRMED": 1,
		"CONFIRNED":   2,
		"COMPLETED":   3,
	}
)

func (x OrderStatusEnum) Enum() *OrderStatusEnum {
	p := new(OrderStatusEnum)
	*p = x
	return p
}

func (x OrderStatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_basic_proto_enumTypes[0].Descriptor()
}

func (OrderStatusEnum) Type() protoreflect.EnumType {
	return &file_basic_proto_enumTypes[0]
}

func (x OrderStatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatusEnum.Descriptor instead.
func (OrderStatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{0}
}

// CUSTOMER
type CustomerAut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginCustomer    string `protobuf:"bytes,1,opt,name=login_customer,json=loginCustomer,proto3" json:"login_customer,omitempty"`
	PasswordCustomer string `protobuf:"bytes,2,opt,name=password_customer,json=passwordCustomer,proto3" json:"password_customer,omitempty"`
}

func (x *CustomerAut) Reset() {
	*x = CustomerAut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerAut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerAut) ProtoMessage() {}

func (x *CustomerAut) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerAut.ProtoReflect.Descriptor instead.
func (*CustomerAut) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerAut) GetLoginCustomer() string {
	if x != nil {
		return x.LoginCustomer
	}
	return ""
}

func (x *CustomerAut) GetPasswordCustomer() string {
	if x != nil {
		return x.PasswordCustomer
	}
	return ""
}

type CustomerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerCountry string `protobuf:"bytes,1,opt,name=customer_country,json=customerCountry,proto3" json:"customer_country,omitempty"`
	CustomerCity    string `protobuf:"bytes,2,opt,name=customer_city,json=customerCity,proto3" json:"customer_city,omitempty"`
}

func (x *CustomerInfo) Reset() {
	*x = CustomerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerInfo) ProtoMessage() {}

func (x *CustomerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerInfo.ProtoReflect.Descriptor instead.
func (*CustomerInfo) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerInfo) GetCustomerCountry() string {
	if x != nil {
		return x.CustomerCountry
	}
	return ""
}

func (x *CustomerInfo) GetCustomerCity() string {
	if x != nil {
		return x.CustomerCity
	}
	return ""
}

type CustomerNew struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerAut  *CustomerAut  `protobuf:"bytes,1,opt,name=customer_aut,json=customerAut,proto3" json:"customer_aut,omitempty"`
	CustomerInfo *CustomerInfo `protobuf:"bytes,2,opt,name=customer_info,json=customerInfo,proto3" json:"customer_info,omitempty"`
}

func (x *CustomerNew) Reset() {
	*x = CustomerNew{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerNew) ProtoMessage() {}

func (x *CustomerNew) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerNew.ProtoReflect.Descriptor instead.
func (*CustomerNew) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerNew) GetCustomerAut() *CustomerAut {
	if x != nil {
		return x.CustomerAut
	}
	return nil
}

func (x *CustomerNew) GetCustomerInfo() *CustomerInfo {
	if x != nil {
		return x.CustomerInfo
	}
	return nil
}

type CustomerChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerAutNew *CustomerAut  `protobuf:"bytes,1,opt,name=customer_aut_new,json=customerAutNew,proto3" json:"customer_aut_new,omitempty"`
	CustomerAutOld *CustomerAut  `protobuf:"bytes,2,opt,name=customer_aut_old,json=customerAutOld,proto3" json:"customer_aut_old,omitempty"`
	CustomerInfo   *CustomerInfo `protobuf:"bytes,3,opt,name=customer_info,json=customerInfo,proto3" json:"customer_info,omitempty"`
}

func (x *CustomerChange) Reset() {
	*x = CustomerChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerChange) ProtoMessage() {}

func (x *CustomerChange) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerChange.ProtoReflect.Descriptor instead.
func (*CustomerChange) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{3}
}

func (x *CustomerChange) GetCustomerAutNew() *CustomerAut {
	if x != nil {
		return x.CustomerAutNew
	}
	return nil
}

func (x *CustomerChange) GetCustomerAutOld() *CustomerAut {
	if x != nil {
		return x.CustomerAutOld
	}
	return nil
}

func (x *CustomerChange) GetCustomerInfo() *CustomerInfo {
	if x != nil {
		return x.CustomerInfo
	}
	return nil
}

// WAREHOUSE
type WarehouseAut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginWarehouse    string `protobuf:"bytes,1,opt,name=login_warehouse,json=loginWarehouse,proto3" json:"login_warehouse,omitempty"`
	PasswordWarehouse string `protobuf:"bytes,2,opt,name=password_warehouse,json=passwordWarehouse,proto3" json:"password_warehouse,omitempty"`
}

func (x *WarehouseAut) Reset() {
	*x = WarehouseAut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WarehouseAut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseAut) ProtoMessage() {}

func (x *WarehouseAut) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseAut.ProtoReflect.Descriptor instead.
func (*WarehouseAut) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{4}
}

func (x *WarehouseAut) GetLoginWarehouse() string {
	if x != nil {
		return x.LoginWarehouse
	}
	return ""
}

func (x *WarehouseAut) GetPasswordWarehouse() string {
	if x != nil {
		return x.PasswordWarehouse
	}
	return ""
}

type WarehouseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WarehouseName       string  `protobuf:"bytes,1,opt,name=warehouse_name,json=warehouseName,proto3" json:"warehouse_name,omitempty"`
	WarehouseCountry    string  `protobuf:"bytes,2,opt,name=warehouse_country,json=warehouseCountry,proto3" json:"warehouse_country,omitempty"`
	WarehouseCity       string  `protobuf:"bytes,3,opt,name=warehouse_city,json=warehouseCity,proto3" json:"warehouse_city,omitempty"`
	WarehouseCommission float32 `protobuf:"fixed32,4,opt,name=warehouse_commission,json=warehouseCommission,proto3" json:"warehouse_commission,omitempty"`
	WarehouseNote       string  `protobuf:"bytes,5,opt,name=warehouse_note,json=warehouseNote,proto3" json:"warehouse_note,omitempty"`
}

func (x *WarehouseInfo) Reset() {
	*x = WarehouseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WarehouseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseInfo) ProtoMessage() {}

func (x *WarehouseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseInfo.ProtoReflect.Descriptor instead.
func (*WarehouseInfo) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{5}
}

func (x *WarehouseInfo) GetWarehouseName() string {
	if x != nil {
		return x.WarehouseName
	}
	return ""
}

func (x *WarehouseInfo) GetWarehouseCountry() string {
	if x != nil {
		return x.WarehouseCountry
	}
	return ""
}

func (x *WarehouseInfo) GetWarehouseCity() string {
	if x != nil {
		return x.WarehouseCity
	}
	return ""
}

func (x *WarehouseInfo) GetWarehouseCommission() float32 {
	if x != nil {
		return x.WarehouseCommission
	}
	return 0
}

func (x *WarehouseInfo) GetWarehouseNote() string {
	if x != nil {
		return x.WarehouseNote
	}
	return ""
}

type WarehouseNew struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WarehouseAut  *WarehouseAut  `protobuf:"bytes,1,opt,name=warehouse_aut,json=warehouseAut,proto3" json:"warehouse_aut,omitempty"`
	WarehouseInfo *WarehouseInfo `protobuf:"bytes,2,opt,name=warehouse_info,json=warehouseInfo,proto3" json:"warehouse_info,omitempty"`
}

func (x *WarehouseNew) Reset() {
	*x = WarehouseNew{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WarehouseNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseNew) ProtoMessage() {}

func (x *WarehouseNew) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseNew.ProtoReflect.Descriptor instead.
func (*WarehouseNew) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{6}
}

func (x *WarehouseNew) GetWarehouseAut() *WarehouseAut {
	if x != nil {
		return x.WarehouseAut
	}
	return nil
}

func (x *WarehouseNew) GetWarehouseInfo() *WarehouseInfo {
	if x != nil {
		return x.WarehouseInfo
	}
	return nil
}

type WarehouseChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WarehouseAutNew *WarehouseAut  `protobuf:"bytes,1,opt,name=warehouse_aut_new,json=warehouseAutNew,proto3" json:"warehouse_aut_new,omitempty"`
	WarehouseAutOld *WarehouseAut  `protobuf:"bytes,2,opt,name=warehouse_aut_old,json=warehouseAutOld,proto3" json:"warehouse_aut_old,omitempty"`
	WarehouseInfo   *WarehouseInfo `protobuf:"bytes,3,opt,name=warehouse_info,json=warehouseInfo,proto3" json:"warehouse_info,omitempty"`
}

func (x *WarehouseChange) Reset() {
	*x = WarehouseChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WarehouseChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseChange) ProtoMessage() {}

func (x *WarehouseChange) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseChange.ProtoReflect.Descriptor instead.
func (*WarehouseChange) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{7}
}

func (x *WarehouseChange) GetWarehouseAutNew() *WarehouseAut {
	if x != nil {
		return x.WarehouseAutNew
	}
	return nil
}

func (x *WarehouseChange) GetWarehouseAutOld() *WarehouseAut {
	if x != nil {
		return x.WarehouseAutOld
	}
	return nil
}

func (x *WarehouseChange) GetWarehouseInfo() *WarehouseInfo {
	if x != nil {
		return x.WarehouseInfo
	}
	return nil
}

type WarehouseWalletInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletMoneyAvailable float32 `protobuf:"fixed32,1,opt,name=wallet_money_available,json=walletMoneyAvailable,proto3" json:"wallet_money_available,omitempty"`
	WalletMoneyBlocked   float32 `protobuf:"fixed32,2,opt,name=wallet_money_blocked,json=walletMoneyBlocked,proto3" json:"wallet_money_blocked,omitempty"`
	CommissionPercentage float32 `protobuf:"fixed32,3,opt,name=commission_percentage,json=commissionPercentage,proto3" json:"commission_percentage,omitempty"`
}

func (x *WarehouseWalletInfo) Reset() {
	*x = WarehouseWalletInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WarehouseWalletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseWalletInfo) ProtoMessage() {}

func (x *WarehouseWalletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseWalletInfo.ProtoReflect.Descriptor instead.
func (*WarehouseWalletInfo) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{8}
}

func (x *WarehouseWalletInfo) GetWalletMoneyAvailable() float32 {
	if x != nil {
		return x.WalletMoneyAvailable
	}
	return 0
}

func (x *WarehouseWalletInfo) GetWalletMoneyBlocked() float32 {
	if x != nil {
		return x.WalletMoneyBlocked
	}
	return 0
}

func (x *WarehouseWalletInfo) GetCommissionPercentage() float32 {
	if x != nil {
		return x.CommissionPercentage
	}
	return 0
}

type ReceivingGoods struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameVendor  string `protobuf:"bytes,1,opt,name=name_vendor,json=nameVendor,proto3" json:"name_vendor,omitempty"`
	NameGoods   string `protobuf:"bytes,2,opt,name=name_goods,json=nameGoods,proto3" json:"name_goods,omitempty"`
	AmountGoods uint32 `protobuf:"varint,3,opt,name=amount_goods,json=amountGoods,proto3" json:"amount_goods,omitempty"`
}

func (x *ReceivingGoods) Reset() {
	*x = ReceivingGoods{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceivingGoods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivingGoods) ProtoMessage() {}

func (x *ReceivingGoods) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivingGoods.ProtoReflect.Descriptor instead.
func (*ReceivingGoods) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{9}
}

func (x *ReceivingGoods) GetNameVendor() string {
	if x != nil {
		return x.NameVendor
	}
	return ""
}

func (x *ReceivingGoods) GetNameGoods() string {
	if x != nil {
		return x.NameGoods
	}
	return ""
}

func (x *ReceivingGoods) GetAmountGoods() uint32 {
	if x != nil {
		return x.AmountGoods
	}
	return 0
}

type ReceivingGoodsARRAY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceivingGoodsArray []*ReceivingGoods `protobuf:"bytes,1,rep,name=receiving_goods_array,json=receivingGoodsArray,proto3" json:"receiving_goods_array,omitempty"`
}

func (x *ReceivingGoodsARRAY) Reset() {
	*x = ReceivingGoodsARRAY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceivingGoodsARRAY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivingGoodsARRAY) ProtoMessage() {}

func (x *ReceivingGoodsARRAY) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivingGoodsARRAY.ProtoReflect.Descriptor instead.
func (*ReceivingGoodsARRAY) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{10}
}

func (x *ReceivingGoodsARRAY) GetReceivingGoodsArray() []*ReceivingGoods {
	if x != nil {
		return x.ReceivingGoodsArray
	}
	return nil
}

// VENDOR
type VendorAut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginVendor    string `protobuf:"bytes,1,opt,name=login_vendor,json=loginVendor,proto3" json:"login_vendor,omitempty"`
	PasswordVendor string `protobuf:"bytes,2,opt,name=password_vendor,json=passwordVendor,proto3" json:"password_vendor,omitempty"`
}

func (x *VendorAut) Reset() {
	*x = VendorAut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VendorAut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorAut) ProtoMessage() {}

func (x *VendorAut) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorAut.ProtoReflect.Descriptor instead.
func (*VendorAut) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{11}
}

func (x *VendorAut) GetLoginVendor() string {
	if x != nil {
		return x.LoginVendor
	}
	return ""
}

func (x *VendorAut) GetPasswordVendor() string {
	if x != nil {
		return x.PasswordVendor
	}
	return ""
}

type VendorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VendorName string `protobuf:"bytes,1,opt,name=vendor_name,json=vendorName,proto3" json:"vendor_name,omitempty"`
}

func (x *VendorInfo) Reset() {
	*x = VendorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VendorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorInfo) ProtoMessage() {}

func (x *VendorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorInfo.ProtoReflect.Descriptor instead.
func (*VendorInfo) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{12}
}

func (x *VendorInfo) GetVendorName() string {
	if x != nil {
		return x.VendorName
	}
	return ""
}

type VendorChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VendorAutNew *VendorAut  `protobuf:"bytes,1,opt,name=vendor_aut_new,json=vendorAutNew,proto3" json:"vendor_aut_new,omitempty"`
	VendorAutOld *VendorAut  `protobuf:"bytes,2,opt,name=vendor_aut_old,json=vendorAutOld,proto3" json:"vendor_aut_old,omitempty"`
	VendorInfo   *VendorInfo `protobuf:"bytes,3,opt,name=vendor_info,json=vendorInfo,proto3" json:"vendor_info,omitempty"`
}

func (x *VendorChange) Reset() {
	*x = VendorChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VendorChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorChange) ProtoMessage() {}

func (x *VendorChange) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorChange.ProtoReflect.Descriptor instead.
func (*VendorChange) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{13}
}

func (x *VendorChange) GetVendorAutNew() *VendorAut {
	if x != nil {
		return x.VendorAutNew
	}
	return nil
}

func (x *VendorChange) GetVendorAutOld() *VendorAut {
	if x != nil {
		return x.VendorAutOld
	}
	return nil
}

func (x *VendorChange) GetVendorInfo() *VendorInfo {
	if x != nil {
		return x.VendorInfo
	}
	return nil
}

type VendorNew struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VendorAut  *VendorAut  `protobuf:"bytes,1,opt,name=vendor_aut,json=vendorAut,proto3" json:"vendor_aut,omitempty"`
	VendorInfo *VendorInfo `protobuf:"bytes,2,opt,name=vendor_info,json=vendorInfo,proto3" json:"vendor_info,omitempty"`
}

func (x *VendorNew) Reset() {
	*x = VendorNew{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VendorNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorNew) ProtoMessage() {}

func (x *VendorNew) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorNew.ProtoReflect.Descriptor instead.
func (*VendorNew) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{14}
}

func (x *VendorNew) GetVendorAut() *VendorAut {
	if x != nil {
		return x.VendorAut
	}
	return nil
}

func (x *VendorNew) GetVendorInfo() *VendorInfo {
	if x != nil {
		return x.VendorInfo
	}
	return nil
}

// OTHERS
type LoginPass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to AccountChoice:
	//
	//	*LoginPass_CustomerLoginPass
	//	*LoginPass_WarehouseLoginPass
	//	*LoginPass_VendorLoginPass
	AccountChoice isLoginPass_AccountChoice `protobuf_oneof:"account_choice"`
}

func (x *LoginPass) Reset() {
	*x = LoginPass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPass) ProtoMessage() {}

func (x *LoginPass) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginPass.ProtoReflect.Descriptor instead.
func (*LoginPass) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{15}
}

func (m *LoginPass) GetAccountChoice() isLoginPass_AccountChoice {
	if m != nil {
		return m.AccountChoice
	}
	return nil
}

func (x *LoginPass) GetCustomerLoginPass() *CustomerAut {
	if x, ok := x.GetAccountChoice().(*LoginPass_CustomerLoginPass); ok {
		return x.CustomerLoginPass
	}
	return nil
}

func (x *LoginPass) GetWarehouseLoginPass() *WarehouseAut {
	if x, ok := x.GetAccountChoice().(*LoginPass_WarehouseLoginPass); ok {
		return x.WarehouseLoginPass
	}
	return nil
}

func (x *LoginPass) GetVendorLoginPass() *VendorAut {
	if x, ok := x.GetAccountChoice().(*LoginPass_VendorLoginPass); ok {
		return x.VendorLoginPass
	}
	return nil
}

type isLoginPass_AccountChoice interface {
	isLoginPass_AccountChoice()
}

type LoginPass_CustomerLoginPass struct {
	CustomerLoginPass *CustomerAut `protobuf:"bytes,1,opt,name=customer_login_pass,json=customerLoginPass,proto3,oneof"`
}

type LoginPass_WarehouseLoginPass struct {
	WarehouseLoginPass *WarehouseAut `protobuf:"bytes,2,opt,name=warehouse_login_pass,json=warehouseLoginPass,proto3,oneof"`
}

type LoginPass_VendorLoginPass struct {
	VendorLoginPass *VendorAut `protobuf:"bytes,3,opt,name=vendor_login_pass,json=vendorLoginPass,proto3,oneof"`
}

func (*LoginPass_CustomerLoginPass) isLoginPass_AccountChoice() {}

func (*LoginPass_WarehouseLoginPass) isLoginPass_AccountChoice() {}

func (*LoginPass_VendorLoginPass) isLoginPass_AccountChoice() {}

type AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to AccountInfo:
	//
	//	*AccountInfo_CustomerChange
	//	*AccountInfo_WarehouseChange
	//	*AccountInfo_VendorChange
	AccountInfo isAccountInfo_AccountInfo `protobuf_oneof:"account_info"`
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{16}
}

func (m *AccountInfo) GetAccountInfo() isAccountInfo_AccountInfo {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

func (x *AccountInfo) GetCustomerChange() *CustomerChange {
	if x, ok := x.GetAccountInfo().(*AccountInfo_CustomerChange); ok {
		return x.CustomerChange
	}
	return nil
}

func (x *AccountInfo) GetWarehouseChange() *WarehouseChange {
	if x, ok := x.GetAccountInfo().(*AccountInfo_WarehouseChange); ok {
		return x.WarehouseChange
	}
	return nil
}

func (x *AccountInfo) GetVendorChange() *VendorChange {
	if x, ok := x.GetAccountInfo().(*AccountInfo_VendorChange); ok {
		return x.VendorChange
	}
	return nil
}

type isAccountInfo_AccountInfo interface {
	isAccountInfo_AccountInfo()
}

type AccountInfo_CustomerChange struct {
	CustomerChange *CustomerChange `protobuf:"bytes,1,opt,name=customer_change,json=customerChange,proto3,oneof"`
}

type AccountInfo_WarehouseChange struct {
	WarehouseChange *WarehouseChange `protobuf:"bytes,2,opt,name=warehouse_change,json=warehouseChange,proto3,oneof"`
}

type AccountInfo_VendorChange struct {
	VendorChange *VendorChange `protobuf:"bytes,3,opt,name=vendor_change,json=vendorChange,proto3,oneof"`
}

func (*AccountInfo_CustomerChange) isAccountInfo_AccountInfo() {}

func (*AccountInfo_WarehouseChange) isAccountInfo_AccountInfo() {}

func (*AccountInfo_VendorChange) isAccountInfo_AccountInfo() {}

type StringJWT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StringJwt string `protobuf:"bytes,1,opt,name=string_jwt,json=stringJwt,proto3" json:"string_jwt,omitempty"`
}

func (x *StringJWT) Reset() {
	*x = StringJWT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringJWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringJWT) ProtoMessage() {}

func (x *StringJWT) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringJWT.ProtoReflect.Descriptor instead.
func (*StringJWT) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{17}
}

func (x *StringJWT) GetStringJwt() string {
	if x != nil {
		return x.StringJwt
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderUuid     string  `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	Location      string  `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	NameGoods     string  `protobuf:"bytes,3,opt,name=name_goods,json=nameGoods,proto3" json:"name_goods,omitempty"`
	TypeGoods     string  `protobuf:"bytes,4,opt,name=type_goods,json=typeGoods,proto3" json:"type_goods,omitempty"`
	NameVendor    string  `protobuf:"bytes,5,opt,name=name_vendor,json=nameVendor,proto3" json:"name_vendor,omitempty"`
	NameWarehouse string  `protobuf:"bytes,6,opt,name=name_warehouse,json=nameWarehouse,proto3" json:"name_warehouse,omitempty"`
	AmountGoods   uint32  `protobuf:"varint,7,opt,name=amount_goods,json=amountGoods,proto3" json:"amount_goods,omitempty"`
	PriceGoods    float32 `protobuf:"fixed32,8,opt,name=price_goods,json=priceGoods,proto3" json:"price_goods,omitempty"`
	Date          string  `protobuf:"bytes,9,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{18}
}

func (x *Order) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *Order) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Order) GetNameGoods() string {
	if x != nil {
		return x.NameGoods
	}
	return ""
}

func (x *Order) GetTypeGoods() string {
	if x != nil {
		return x.TypeGoods
	}
	return ""
}

func (x *Order) GetNameVendor() string {
	if x != nil {
		return x.NameVendor
	}
	return ""
}

func (x *Order) GetNameWarehouse() string {
	if x != nil {
		return x.NameWarehouse
	}
	return ""
}

func (x *Order) GetAmountGoods() uint32 {
	if x != nil {
		return x.AmountGoods
	}
	return 0
}

func (x *Order) GetPriceGoods() float32 {
	if x != nil {
		return x.PriceGoods
	}
	return 0
}

func (x *Order) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Orders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
}

func (x *Orders) Reset() {
	*x = Orders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Orders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orders) ProtoMessage() {}

func (x *Orders) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orders.ProtoReflect.Descriptor instead.
func (*Orders) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{19}
}

func (x *Orders) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrderStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderStatus OrderStatusEnum `protobuf:"varint,1,opt,name=order_status,json=orderStatus,proto3,enum=basic.OrderStatusEnum" json:"order_status,omitempty"`
}

func (x *OrderStatus) Reset() {
	*x = OrderStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatus) ProtoMessage() {}

func (x *OrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatus.ProtoReflect.Descriptor instead.
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{20}
}

func (x *OrderStatus) GetOrderStatus() OrderStatusEnum {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatusEnum_UNSPECIFIED
}

type NewOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameWarehouse string `protobuf:"bytes,1,opt,name=name_warehouse,json=nameWarehouse,proto3" json:"name_warehouse,omitempty"`
	NameVendor    string `protobuf:"bytes,2,opt,name=name_vendor,json=nameVendor,proto3" json:"name_vendor,omitempty"`
	NameGoods     string `protobuf:"bytes,3,opt,name=name_goods,json=nameGoods,proto3" json:"name_goods,omitempty"`
	AmountGoods   uint32 `protobuf:"varint,4,opt,name=amount_goods,json=amountGoods,proto3" json:"amount_goods,omitempty"`
}

func (x *NewOrder) Reset() {
	*x = NewOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewOrder) ProtoMessage() {}

func (x *NewOrder) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewOrder.ProtoReflect.Descriptor instead.
func (*NewOrder) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{21}
}

func (x *NewOrder) GetNameWarehouse() string {
	if x != nil {
		return x.NameWarehouse
	}
	return ""
}

func (x *NewOrder) GetNameVendor() string {
	if x != nil {
		return x.NameVendor
	}
	return ""
}

func (x *NewOrder) GetNameGoods() string {
	if x != nil {
		return x.NameGoods
	}
	return ""
}

func (x *NewOrder) GetAmountGoods() uint32 {
	if x != nil {
		return x.AmountGoods
	}
	return 0
}

type NewOrderARRAY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewOrder []*NewOrder `protobuf:"bytes,1,rep,name=new_order,json=newOrder,proto3" json:"new_order,omitempty"`
}

func (x *NewOrderARRAY) Reset() {
	*x = NewOrderARRAY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewOrderARRAY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewOrderARRAY) ProtoMessage() {}

func (x *NewOrderARRAY) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewOrderARRAY.ProtoReflect.Descriptor instead.
func (*NewOrderARRAY) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{22}
}

func (x *NewOrderARRAY) GetNewOrder() []*NewOrder {
	if x != nil {
		return x.NewOrder
	}
	return nil
}

type AddToOrderARRAY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderUuid string      `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	NewOrder  []*NewOrder `protobuf:"bytes,2,rep,name=new_order,json=newOrder,proto3" json:"new_order,omitempty"`
}

func (x *AddToOrderARRAY) Reset() {
	*x = AddToOrderARRAY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToOrderARRAY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToOrderARRAY) ProtoMessage() {}

func (x *AddToOrderARRAY) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToOrderARRAY.ProtoReflect.Descriptor instead.
func (*AddToOrderARRAY) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{23}
}

func (x *AddToOrderARRAY) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *AddToOrderARRAY) GetNewOrder() []*NewOrder {
	if x != nil {
		return x.NewOrder
	}
	return nil
}

type OrderUuid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderUuid string `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
}

func (x *OrderUuid) Reset() {
	*x = OrderUuid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderUuid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUuid) ProtoMessage() {}

func (x *OrderUuid) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUuid.ProtoReflect.Descriptor instead.
func (*OrderUuid) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{24}
}

func (x *OrderUuid) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

type WalletInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AmountMoney  float32 `protobuf:"fixed32,1,opt,name=amount_money,json=amountMoney,proto3" json:"amount_money,omitempty"`
	BlockedMoney float32 `protobuf:"fixed32,2,opt,name=blocked_money,json=blockedMoney,proto3" json:"blocked_money,omitempty"`
}

func (x *WalletInfo) Reset() {
	*x = WalletInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletInfo) ProtoMessage() {}

func (x *WalletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletInfo.ProtoReflect.Descriptor instead.
func (*WalletInfo) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{25}
}

func (x *WalletInfo) GetAmountMoney() float32 {
	if x != nil {
		return x.AmountMoney
	}
	return 0
}

func (x *WalletInfo) GetBlockedMoney() float32 {
	if x != nil {
		return x.BlockedMoney
	}
	return 0
}

type CountryCityPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City    string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *CountryCityPair) Reset() {
	*x = CountryCityPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountryCityPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryCityPair) ProtoMessage() {}

func (x *CountryCityPair) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryCityPair.ProtoReflect.Descriptor instead.
func (*CountryCityPair) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{26}
}

func (x *CountryCityPair) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CountryCityPair) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type CountryCityPairs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryCityPairs []*CountryCityPair `protobuf:"bytes,1,rep,name=country_city_pairs,json=countryCityPairs,proto3" json:"country_city_pairs,omitempty"`
}

func (x *CountryCityPairs) Reset() {
	*x = CountryCityPairs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountryCityPairs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryCityPairs) ProtoMessage() {}

func (x *CountryCityPairs) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryCityPairs.ProtoReflect.Descriptor instead.
func (*CountryCityPairs) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{27}
}

func (x *CountryCityPairs) GetCountryCityPairs() []*CountryCityPair {
	if x != nil {
		return x.CountryCityPairs
	}
	return nil
}

type Goods struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameWarehouse string  `protobuf:"bytes,1,opt,name=name_warehouse,json=nameWarehouse,proto3" json:"name_warehouse,omitempty"`
	Location      string  `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	NameVendor    string  `protobuf:"bytes,3,opt,name=name_vendor,json=nameVendor,proto3" json:"name_vendor,omitempty"`
	TypeGoods     string  `protobuf:"bytes,4,opt,name=type_goods,json=typeGoods,proto3" json:"type_goods,omitempty"`
	NameGoods     string  `protobuf:"bytes,5,opt,name=name_goods,json=nameGoods,proto3" json:"name_goods,omitempty"`
	InfoGoods     string  `protobuf:"bytes,6,opt,name=info_goods,json=infoGoods,proto3" json:"info_goods,omitempty"`
	PriceGoods    float32 `protobuf:"fixed32,7,opt,name=price_goods,json=priceGoods,proto3" json:"price_goods,omitempty"`
	AmountGoods   uint32  `protobuf:"varint,8,opt,name=amount_goods,json=amountGoods,proto3" json:"amount_goods,omitempty"`
}

func (x *Goods) Reset() {
	*x = Goods{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Goods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goods) ProtoMessage() {}

func (x *Goods) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goods.ProtoReflect.Descriptor instead.
func (*Goods) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{28}
}

func (x *Goods) GetNameWarehouse() string {
	if x != nil {
		return x.NameWarehouse
	}
	return ""
}

func (x *Goods) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Goods) GetNameVendor() string {
	if x != nil {
		return x.NameVendor
	}
	return ""
}

func (x *Goods) GetTypeGoods() string {
	if x != nil {
		return x.TypeGoods
	}
	return ""
}

func (x *Goods) GetNameGoods() string {
	if x != nil {
		return x.NameGoods
	}
	return ""
}

func (x *Goods) GetInfoGoods() string {
	if x != nil {
		return x.InfoGoods
	}
	return ""
}

func (x *Goods) GetPriceGoods() float32 {
	if x != nil {
		return x.PriceGoods
	}
	return 0
}

func (x *Goods) GetAmountGoods() uint32 {
	if x != nil {
		return x.AmountGoods
	}
	return 0
}

type GoodsArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Goods []*Goods `protobuf:"bytes,1,rep,name=goods,proto3" json:"goods,omitempty"`
}

func (x *GoodsArray) Reset() {
	*x = GoodsArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_basic_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsArray) ProtoMessage() {}

func (x *GoodsArray) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsArray.ProtoReflect.Descriptor instead.
func (*GoodsArray) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{29}
}

func (x *GoodsArray) GetGoods() []*Goods {
	if x != nil {
		return x.Goods
	}
	return nil
}

var File_basic_proto protoreflect.FileDescriptor

var file_basic_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x22, 0x61, 0x0a, 0x0b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x41, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x22, 0x5e, 0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x63,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x43, 0x69, 0x74, 0x79, 0x22, 0x7e, 0x0a, 0x0b, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x12, 0x35, 0x0a, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x5f, 0x61, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x41, 0x75, 0x74,
	0x52, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x41, 0x75, 0x74, 0x12, 0x38, 0x0a,
	0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xc6, 0x01, 0x0a, 0x0e, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x3c, 0x0a, 0x10, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x61, 0x75, 0x74, 0x5f, 0x6e, 0x65, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x41, 0x75, 0x74, 0x52, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x41, 0x75, 0x74, 0x4e, 0x65, 0x77, 0x12, 0x3c, 0x0a, 0x10, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x61, 0x75, 0x74, 0x5f, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x41, 0x75, 0x74, 0x52, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x41, 0x75, 0x74, 0x4f, 0x6c, 0x64, 0x12, 0x38, 0x0a, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x66, 0x0a, 0x0c, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x75, 0x74,
	0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x57,
	0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x22, 0xe4, 0x01, 0x0a, 0x0d, 0x57, 0x61, 0x72,
	0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x2b, 0x0a, 0x11, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x77, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x25,
	0x0a, 0x0e, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x43, 0x69, 0x74, 0x79, 0x12, 0x31, 0x0a, 0x14, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x13, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x61, 0x72, 0x65,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x22,
	0x85, 0x01, 0x0a, 0x0c, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4e, 0x65, 0x77,
	0x12, 0x38, 0x0a, 0x0d, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x61, 0x75,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e,
	0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x75, 0x74, 0x52, 0x0c, 0x77, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x75, 0x74, 0x12, 0x3b, 0x0a, 0x0e, 0x77, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x57, 0x61, 0x72, 0x65, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xd0, 0x01, 0x0a, 0x0f, 0x57, 0x61, 0x72, 0x65,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x11, 0x77,
	0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x5f, 0x6e, 0x65, 0x77,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x57,
	0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x75, 0x74, 0x52, 0x0f, 0x77, 0x61, 0x72,
	0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x75, 0x74, 0x4e, 0x65, 0x77, 0x12, 0x3f, 0x0a, 0x11,
	0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x5f, 0x6f, 0x6c,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e,
	0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x75, 0x74, 0x52, 0x0f, 0x77, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x75, 0x74, 0x4f, 0x6c, 0x64, 0x12, 0x3b, 0x0a,
	0x0e, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x57, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x77, 0x61, 0x72,
	0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xb2, 0x01, 0x0a, 0x13, 0x57,
	0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x34, 0x0a, 0x16, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x14, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x12, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x33, 0x0a, 0x15, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x22,
	0x73, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x22, 0x60, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e,
	0x67, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x41, 0x52, 0x52, 0x41, 0x59, 0x12, 0x49, 0x0a, 0x15, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x61,
	0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x52, 0x13, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e, 0x67, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x22, 0x57, 0x0a, 0x09, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x41, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x76, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x22,
	0x2d, 0x0a, 0x0a, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a,
	0x0b, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb2,
	0x01, 0x0a, 0x0c, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x36, 0x0a, 0x0e, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x61, 0x75, 0x74, 0x5f, 0x6e, 0x65,
	0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e,
	0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x75, 0x74, 0x52, 0x0c, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x41, 0x75, 0x74, 0x4e, 0x65, 0x77, 0x12, 0x36, 0x0a, 0x0e, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x5f, 0x61, 0x75, 0x74, 0x5f, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x75,
	0x74, 0x52, 0x0c, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x75, 0x74, 0x4f, 0x6c, 0x64, 0x12,
	0x32, 0x0a, 0x0b, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x56, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x70, 0x0a, 0x09, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x4e, 0x65, 0x77,
	0x12, 0x2f, 0x0a, 0x0a, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x61, 0x75, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x56, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x41, 0x75, 0x74, 0x52, 0x09, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x75,
	0x74, 0x12, 0x32, 0x0a, 0x0b, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x56,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xec, 0x01, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50,
	0x61, 0x73, 0x73, 0x12, 0x44, 0x0a, 0x13, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x41, 0x75, 0x74, 0x48, 0x00, 0x52, 0x11, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x12, 0x47, 0x0a, 0x14, 0x77, 0x61, 0x72,
	0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e,
	0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x41, 0x75, 0x74, 0x48, 0x00, 0x52, 0x12,
	0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61,
	0x73, 0x73, 0x12, 0x3e, 0x0a, 0x11, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x41, 0x75, 0x74, 0x48,
	0x00, 0x52, 0x0f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61,
	0x73, 0x73, 0x42, 0x10, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x63, 0x68,
	0x6f, 0x69, 0x63, 0x65, 0x22, 0xe0, 0x01, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x40, 0x0a, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x43, 0x0a, 0x10, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x77, 0x61, 0x72, 0x65,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x76,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x56, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x76, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x2a, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x4a, 0x57, 0x54, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x6a,
	0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x4a, 0x77, 0x74, 0x22, 0xa0, 0x02, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a,
	0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65,
	0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x5f,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x79, 0x70,
	0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x76,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d,
	0x65, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x61, 0x6d, 0x65, 0x5f,
	0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x2e, 0x0a, 0x06, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x12, 0x24, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0x48, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45,
	0x6e, 0x75, 0x6d, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x94, 0x01, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a,
	0x0e, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x57, 0x61, 0x72, 0x65, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x76, 0x65, 0x6e,
	0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x56,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x22, 0x3d, 0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x41, 0x52, 0x52, 0x41, 0x59, 0x12, 0x2c, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x2e, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x08, 0x6e, 0x65,
	0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x5e, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x41, 0x52, 0x52, 0x41, 0x59, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x2e, 0x4e, 0x65, 0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x08, 0x6e, 0x65,
	0x77, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55,
	0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x75,
	0x69, 0x64, 0x22, 0x54, 0x0a, 0x0a, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x6d,
	0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x65, 0x64, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x22, 0x3f, 0x0a, 0x0f, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x43, 0x69, 0x74, 0x79, 0x50, 0x61, 0x69, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x22, 0x58, 0x0a, 0x10, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x43, 0x69, 0x74, 0x79, 0x50, 0x61, 0x69, 0x72, 0x73, 0x12, 0x44, 0x0a,
	0x12, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x61,
	0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x69, 0x74, 0x79, 0x50, 0x61, 0x69,
	0x72, 0x52, 0x10, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x69, 0x74, 0x79, 0x50, 0x61,
	0x69, 0x72, 0x73, 0x22, 0x8c, 0x02, 0x0a, 0x05, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x25, 0x0a,
	0x0e, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x57, 0x61, 0x72, 0x65, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x6e, 0x64, 0x6f,
	0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x79, 0x70, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x66, 0x6f, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x22, 0x30, 0x0a, 0x0a, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x12, 0x22, 0x0a, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x05, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x2a, 0x51, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x43, 0x4f,
	0x4e, 0x46, 0x49, 0x52, 0x4d, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4e,
	0x46, 0x49, 0x52, 0x4e, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50,
	0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x6c, 0x69, 0x70, 0x68, 0x75, 0x6c, 0x6b, 0x6f,
	0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2d, 0x65, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_basic_proto_rawDescOnce sync.Once
	file_basic_proto_rawDescData = file_basic_proto_rawDesc
)

func file_basic_proto_rawDescGZIP() []byte {
	file_basic_proto_rawDescOnce.Do(func() {
		file_basic_proto_rawDescData = protoimpl.X.CompressGZIP(file_basic_proto_rawDescData)
	})
	return file_basic_proto_rawDescData
}

var file_basic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_basic_proto_goTypes = []interface{}{
	(OrderStatusEnum)(0),        // 0: basic.OrderStatusEnum
	(*CustomerAut)(nil),         // 1: basic.CustomerAut
	(*CustomerInfo)(nil),        // 2: basic.CustomerInfo
	(*CustomerNew)(nil),         // 3: basic.CustomerNew
	(*CustomerChange)(nil),      // 4: basic.CustomerChange
	(*WarehouseAut)(nil),        // 5: basic.WarehouseAut
	(*WarehouseInfo)(nil),       // 6: basic.WarehouseInfo
	(*WarehouseNew)(nil),        // 7: basic.WarehouseNew
	(*WarehouseChange)(nil),     // 8: basic.WarehouseChange
	(*WarehouseWalletInfo)(nil), // 9: basic.WarehouseWalletInfo
	(*ReceivingGoods)(nil),      // 10: basic.ReceivingGoods
	(*ReceivingGoodsARRAY)(nil), // 11: basic.ReceivingGoodsARRAY
	(*VendorAut)(nil),           // 12: basic.VendorAut
	(*VendorInfo)(nil),          // 13: basic.VendorInfo
	(*VendorChange)(nil),        // 14: basic.VendorChange
	(*VendorNew)(nil),           // 15: basic.VendorNew
	(*LoginPass)(nil),           // 16: basic.LoginPass
	(*AccountInfo)(nil),         // 17: basic.AccountInfo
	(*StringJWT)(nil),           // 18: basic.StringJWT
	(*Order)(nil),               // 19: basic.Order
	(*Orders)(nil),              // 20: basic.Orders
	(*OrderStatus)(nil),         // 21: basic.OrderStatus
	(*NewOrder)(nil),            // 22: basic.NewOrder
	(*NewOrderARRAY)(nil),       // 23: basic.NewOrderARRAY
	(*AddToOrderARRAY)(nil),     // 24: basic.AddToOrderARRAY
	(*OrderUuid)(nil),           // 25: basic.OrderUuid
	(*WalletInfo)(nil),          // 26: basic.WalletInfo
	(*CountryCityPair)(nil),     // 27: basic.CountryCityPair
	(*CountryCityPairs)(nil),    // 28: basic.CountryCityPairs
	(*Goods)(nil),               // 29: basic.Goods
	(*GoodsArray)(nil),          // 30: basic.GoodsArray
}
var file_basic_proto_depIdxs = []int32{
	1,  // 0: basic.CustomerNew.customer_aut:type_name -> basic.CustomerAut
	2,  // 1: basic.CustomerNew.customer_info:type_name -> basic.CustomerInfo
	1,  // 2: basic.CustomerChange.customer_aut_new:type_name -> basic.CustomerAut
	1,  // 3: basic.CustomerChange.customer_aut_old:type_name -> basic.CustomerAut
	2,  // 4: basic.CustomerChange.customer_info:type_name -> basic.CustomerInfo
	5,  // 5: basic.WarehouseNew.warehouse_aut:type_name -> basic.WarehouseAut
	6,  // 6: basic.WarehouseNew.warehouse_info:type_name -> basic.WarehouseInfo
	5,  // 7: basic.WarehouseChange.warehouse_aut_new:type_name -> basic.WarehouseAut
	5,  // 8: basic.WarehouseChange.warehouse_aut_old:type_name -> basic.WarehouseAut
	6,  // 9: basic.WarehouseChange.warehouse_info:type_name -> basic.WarehouseInfo
	10, // 10: basic.ReceivingGoodsARRAY.receiving_goods_array:type_name -> basic.ReceivingGoods
	12, // 11: basic.VendorChange.vendor_aut_new:type_name -> basic.VendorAut
	12, // 12: basic.VendorChange.vendor_aut_old:type_name -> basic.VendorAut
	13, // 13: basic.VendorChange.vendor_info:type_name -> basic.VendorInfo
	12, // 14: basic.VendorNew.vendor_aut:type_name -> basic.VendorAut
	13, // 15: basic.VendorNew.vendor_info:type_name -> basic.VendorInfo
	1,  // 16: basic.LoginPass.customer_login_pass:type_name -> basic.CustomerAut
	5,  // 17: basic.LoginPass.warehouse_login_pass:type_name -> basic.WarehouseAut
	12, // 18: basic.LoginPass.vendor_login_pass:type_name -> basic.VendorAut
	4,  // 19: basic.AccountInfo.customer_change:type_name -> basic.CustomerChange
	8,  // 20: basic.AccountInfo.warehouse_change:type_name -> basic.WarehouseChange
	14, // 21: basic.AccountInfo.vendor_change:type_name -> basic.VendorChange
	19, // 22: basic.Orders.orders:type_name -> basic.Order
	0,  // 23: basic.OrderStatus.order_status:type_name -> basic.OrderStatusEnum
	22, // 24: basic.NewOrderARRAY.new_order:type_name -> basic.NewOrder
	22, // 25: basic.AddToOrderARRAY.new_order:type_name -> basic.NewOrder
	27, // 26: basic.CountryCityPairs.country_city_pairs:type_name -> basic.CountryCityPair
	29, // 27: basic.GoodsArray.goods:type_name -> basic.Goods
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_basic_proto_init() }
func file_basic_proto_init() {
	if File_basic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_basic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerAut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerNew); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WarehouseAut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WarehouseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WarehouseNew); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WarehouseChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WarehouseWalletInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceivingGoods); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceivingGoodsARRAY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VendorAut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VendorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VendorChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VendorNew); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginPass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringJWT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Orders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewOrderARRAY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToOrderARRAY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderUuid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalletInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountryCityPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountryCityPairs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Goods); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_basic_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_basic_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*LoginPass_CustomerLoginPass)(nil),
		(*LoginPass_WarehouseLoginPass)(nil),
		(*LoginPass_VendorLoginPass)(nil),
	}
	file_basic_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*AccountInfo_CustomerChange)(nil),
		(*AccountInfo_WarehouseChange)(nil),
		(*AccountInfo_VendorChange)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_basic_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_basic_proto_goTypes,
		DependencyIndexes: file_basic_proto_depIdxs,
		EnumInfos:         file_basic_proto_enumTypes,
		MessageInfos:      file_basic_proto_msgTypes,
	}.Build()
	File_basic_proto = out.File
	file_basic_proto_rawDesc = nil
	file_basic_proto_goTypes = nil
	file_basic_proto_depIdxs = nil
}
